/*
 *	BIRD Client -- Reply codes for communication between client and daemon
 *
 *	(c) 2016 CZ.NIC z.s.p.o.
 *
 *	Can be freely distributed and used under the terms of the GNU GPL.
 */

#ifndef _BIRD_REPLY_CODES_H_
#define _BIRD_REPLY_CODES_H_

/*
Reply codes of BIRD command-line interface
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0xxx	Action suceessfully completed
1xxx	Table entry
2xxx	Table heading
3xxx	Internal messages
8xxx	Run-time error
9xxx	Parse-time error
<space>	Continuation
+	Spontaneous printout
*/

enum reply_code {
  RC_OK = 0,
  RC_WELCOME = 1,
  RC_READING_CONFIGURATION = 2,
  RC_RECONFIGURED = 3,
  RC_RECONFIGURATION_IN_PROGRESS = 4,
  RC_RECONFIGURATION_ALREADY_IN_PROGRESS, QUEUEING = 5,
  RC_RECONFIGURATION_IGNORED_SHUTTING_DOWN = 6,
  RC_SHUTDOWN_ORDERED = 7,
  RC_ALREADY_DISABLED = 8,
  RC_DISABLED = 9,
  RC_ALREADY_ENABLED = 10,
  RC_ENABLED = 11,
  RC_RESTARTED = 12,
  RC_STATUS_REPORT = 13,
  RC_ROUTE_COUNT = 14,
  RC_RELOADING = 15,
  RC_ACCESS_RESTRICTED = 16,
  RC_RECONFIGURATION_ALREADY_IN_PROGRESS_REMOVING_QUEUED_CONFIG = 17,
  RC_RECONFIGURATION_CONFIRMED = 18,
  RC_NOTHING_TO_DO_CONFIGURE_UNDO_CONFIRM = 19,
  RC_CONFIGURATION_OK = 20,
  RC_UNDO_REQUESTED = 21,
  RC_UNDO_SCHEDULED = 22,
  RC_EVALUATION_OF_EXPRESSION = 23,
  RC_GRACEFUL_RESTART_STATUS_REPORT = 24,

  RC_BIRD_VERSION = 1000,
  RC_INTERFACE_LIST = 1001,
  RC_PROTOCOL_LIST = 1002,
  RC_INTERFACE_ADDRESS = 1003,
  RC_INTERFACE_FLAGS = 1004,
  RC_INTERFACE_SUMMARY = 1005,
  RC_PROTOCOL_DETAILS = 1006,
  RC_ROUTE_LIST = 1007,
  RC_ROUTE_DETAILS = 1008,
  RC_STATIC_ROUTE_LIST = 1009,
  RC_SYMBOL_LIST = 1010,
  RC_UPTIME = 1011,
  RC_ROUTE_EXTENDED_ATTRIBUTE_LIST = 1012,
  RC_SHOW_OSPF_NEIGHBORS = 1013,
  RC_SHOW_OSPF = 1014,
  RC_SHOW_OSPF_INTERFACE = 1015,
  RC_SHOW_OSPF_STATE_TOPOLOGY = 1016,
  RC_SHOW_OSPF_LSADB = 1017,
  RC_SHOW_MEMORY = 1018,
  RC_SHOW_ROA_LIST = 1019,
  RC_SHOW_BFD_SESSIONS = 1020,
  RC_SHOW_RIP_INTERFACE = 1021,
  RC_SHOW_RIP_NEIGHBORS = 1022,

  RC_BIRD_VERSION_NUM = 3000,   /* This begins the symbol dump */
  RC_TABLE_NAME = 3001,
  RC_PROTOCOL_NAME = 3002,
  RC_FILTER_NAME = 3003,
  RC_FUNCTION_NAME = 3004,
  RC_CONSTANT_NAME = 3005,
  RC_VARIABLE_NAME = 3006,
  RC_TEMPLATE_NAME = 3007,
  RC_INTERFACE_NAME = 3008,
  RC_DUMP_DONE = 3009,		/* This ends the symbol dump */
  RC_NOTIFY = 3010, 		/* Daemon notifies the client about new symbol set */

  RC_REPLY_TOO_LONG = 8000,
  RC_ROUTE_NOT_FOUND = 8001,
  RC_CONFIGURATION_FILE_ERROR = 8002,
  RC_NO_PROTOCOLS_MATCH = 8003,
  RC_STOPPED_DUE_TO_RECONFIGURATION = 8004,
  RC_PROTOCOL_IS_DOWN_CANNOT_DUMP = 8005,
  RC_RELOAD_FAILED = 8006,
  RC_ACCESS_DENIED = 8007,
  RC_EVALUATION_RUNTIME_ERROR = 8008,

  RC_COMMAND_TOO_LONG = 9000,
  RC_PARSE_ERROR = 9001,
  RC_INVALID_SYMBOL_TYPE = 9002,
};

#endif

