/*
 *	Filters: Data classes
 *
 *	(c) 1998       Pavel Machek <pavel@ucw.cz>
 *	(c) 2019--2026 Maria Matejka <mq@jmq.cz>
 *
 *	Can be freely distributed and used under the terms of the GNU GPL.
 */

//#define PARSER 1

#include "nest/bird.h"
#include "lib/lists.h"
#include "lib/resource.h"
#include "lib/socket.h"
#include "lib/string.h"
#include "lib/unaligned.h"
#include "lib/net.h"
#include "lib/ip.h"
#include "nest/route.h"
#include "nest/protocol.h"
#include "nest/iface.h"
#include "nest/attrs.h"
#include "filter/filter.h"
#include "filter/f-inst.h"
#include "filter/data.h"
#include "conf/conf.h"
//#include "conf/cf-parse.tab.h"

#include "filter/class-m4-auto-pre.c"

SUBLAMBDA(COMPARE, int, F_CLASS_COMPARE);
SUBLAMBDA(SAME, bool, F_CLASS_COMPARE);
SUBLAMBDA(HASHVAL, u64, F_CLASS_HASH);

#ifdef M4_AUTO
/*
 ************* M4 definitions **************
 */

/* Autogenerated header file header */
AUX_SECTION(INCH, H_BEGIN, [[
/*
 *	Filters: Data classes
 *
 *	Automatically generated from ]]m4_builtin(__file__)[[ by ]]AUX_MACROSET()[[
 */
#ifndef _BIRD_FILTER_CLASS_M4_AUTO_H_
#define _BIRD_FILTER_CLASS_M4_AUTO_H_
]],);

AUX_END_SECTION(INCH, H_END,,[[
#endif
]]);

/* Enum of T_* class IDs */
AUX_SECTION(INCH, H_ENUM,[[
PACKED enum f_type {
]],[[
  T_SET,
  T_PREFIX_SET,
  T__MAX,
};
]]);

/* Actual filter value */
AUX_SECTION(INCH, H_VAL_UNION,[[
struct f_val {
  enum f_type type;
  union {
    uint i;
    u64 ec;
    lcomm lc;
    vpn_rd rd;
    ip_addr ip;
    mac_addr mac;
    const net_addr *net;
    const char *s;
    const struct adata *bs;
    const struct f_tree *t;
    const struct f_trie *ti;
    const struct adata *ad;
    const struct f_path_mask *path_mask;
    struct f_path_mask_item pmi;
    struct rte *rte;
]],[[
  } val;
};
]]);

/* Class contents */
AUX_SECTION(INCH, H_CLASS,[[/* Detailed type/class definitions */]],);
H_CLASS();

/* Standard class operations */
#define F_CLASS_COMPARE			const struct f_val *v1, const struct f_val *v2
#define F_CLASS_HASH			u64 seed, const struct f_val *v

struct f_class {
  enum f_type id;			/* T_* for static types */
  byte ea_type;				/* EAF_TYPE_* */
  bool hidden;				/* Inaccessible for users from config */
  bool legacy_kw;			/* Accessed from type_kw in parser */
  int size;				/* Output of sizeof, aligned to sizeof(int) */
  const char *name;			/* String name */
  const char *pretty_name;		/* More descriptive name */
  struct f_val empty;			/* Default value of uninitialized variables */
  int (*compare)(F_CLASS_COMPARE);	/* Return 1 if v1 > v2, -1 if v1 < v2, 0 otherwise */
  bool (*same)(F_CLASS_COMPARE);	/* Return true if v1 == v2, false otherwise
					   All classes must have either &compare or &same. */
  u64 (*hash)(F_CLASS_HASH);		/* Mix in a hash value */
};

AUX_MUTE();

/* Collect class information at the beginning */
m4_define(FC_SN,[[m4_define([[THIS_CLASS_NAME]],$1)]]);
m4_define(FC_TYPE,[[m4_define([[THIS_CLASS_TYPE]],$1)]]);

/* Get Type By ID array */
AUX_SECTION(POSTC, C_BASE_TYPES,[[
const struct f_class *f_base_types[T__MAX] = {
]],[[
};
]]);

/* Consistency check in tests */
AUX_SECTION(TESTC, C_CONSISTENCY,[[
int t_types_consistency(void)
{
]],[[
  return 1;
}
]]);

/* Actually use the ID */
m4_define(FC_ID,[[
m4_define([[THIS_CLASS_VAL]],v_$1)
H_ENUM()  $1,
H_VAL_UNION()    THIS_CLASS_TYPE() v_$1;
C_BASE_TYPES  [$1] = &THIS_CLASS_NAME,

C_CONSISTENCY()
  bt_assert_msg(f_base_types[$1]->name, "Type $1 (THIS_CLASS_NAME) has no defined name");
  bt_assert_msg((
      f_base_types[$1]->hidden ||
      f_base_types[$1]->compare ||
      f_base_types[$1]->same
      ), "Type $1 (THIS_CLASS_NAME / %s) is not hidden and has neither compare(), nor same()", f_base_types[$1]->name);

AUX_MUTE()
]]);

m4_define(VAL,[[v->val.THIS_CLASS_VAL()]])
m4_define(VAL1,[[v1->val.THIS_CLASS_VAL()]])
m4_define(VAL2,[[v2->val.THIS_CLASS_VAL()]])

#else
#define FC_SN(x)	x
#define FC_ID(x)	.id = x
#define FC_TYPE(x)	.size = sizeof(x)
#endif

static bool
void_same(const struct f_val *v1 UNUSED, const struct f_val *v2 UNUSED)
{ return true; }

static u64
void_hash(u64 seed, const struct f_val *v UNUSED)
{ return seed; }

static const struct f_class FC_SN(f_type_void) = {
  FC_TYPE(int),
  FC_ID(T_VOID),
  .name = "void",
  .same = &void_same,
  .hash = &void_hash,
};

static const struct f_class FC_SN(f_type_none) = {
  FC_TYPE(int),
  FC_ID(T_NONE),
  .hidden = true,
  .name = "none",
};

static const struct f_class FC_SN(f_type_int) = {
  FC_TYPE(int),
  FC_ID(T_INT),
  .ea_type = EAF_TYPE_INT,
  .legacy_kw = true,
  .name = "int",
  .pretty_name = "Integer",
  .compare = COMPARE(uint_cmp(VAL1, VAL2)),
  .hash = HASHVAL(u64_hash0(VAL, HASH_PARAM, seed)),
};

static const struct f_class FC_SN(f_type_bool) = {
  FC_TYPE(bool),
  FC_ID(T_BOOL),
  .legacy_kw = true,
  .name = "bool",
  .compare = COMPARE(uint_cmp(VAL1, VAL2)),
  .hash = HASHVAL(u64_hash0(VAL, HASH_PARAM, seed)),
};

static const struct f_class FC_SN(f_type_pair) = {
  FC_TYPE(int),
  FC_ID(T_PAIR),
  .legacy_kw = true,
  .name = "pair",
  .compare = COMPARE(uint_cmp(VAL1, VAL2)),
  .hash = HASHVAL(u64_hash0(VAL, HASH_PARAM, seed)),
};

static const struct f_class FC_SN(f_type_quad) = {
  FC_TYPE(int),
  FC_ID(T_QUAD),
  .ea_type = EAF_TYPE_ROUTER_ID,
  .legacy_kw = true,
  .name = "quad",
  .compare = COMPARE(uint_cmp(VAL1, VAL2)),
  .hash = HASHVAL(u64_hash0(VAL, HASH_PARAM, seed)),
};

static const struct f_class FC_SN(f_type_enum_lo) = {
  FC_TYPE(int),
  FC_ID(T_ENUM_LO),
  .hidden = true,
  .name = "enum __lo",
};

static const struct f_class FC_SN(f_type_enum_rts) = {
  FC_TYPE(int),
  FC_ID(T_ENUM_RTS),
  .name = "enum rts",
  .compare = COMPARE(uint_cmp(VAL1, VAL2)),
  .hash = HASHVAL(u64_hash0(VAL, HASH_PARAM, seed)),
};

static const struct f_class FC_SN(f_type_enum_bgp_origin) = {
  FC_TYPE(int),
  FC_ID(T_ENUM_BGP_ORIGIN),
  .name = "enum bgp_origin",
  .compare = COMPARE(uint_cmp(VAL1, VAL2)),
  .hash = HASHVAL(u64_hash0(VAL, HASH_PARAM, seed)),
};

static const struct f_class FC_SN(f_type_enum_scope) = {
  FC_TYPE(int),
  FC_ID(T_ENUM_SCOPE),
  .name = "enum scope",
  .compare = COMPARE(uint_cmp(VAL1, VAL2)),
  .hash = HASHVAL(u64_hash0(VAL, HASH_PARAM, seed)),
};

static const struct f_class FC_SN(f_type_enum_rtd) = {
  FC_TYPE(int),
  FC_ID(T_ENUM_RTD),
  .name = "enum rtd",
  .compare = COMPARE(uint_cmp(VAL1, VAL2)),
  .hash = HASHVAL(u64_hash0(VAL, HASH_PARAM, seed)),
};

static const struct f_class FC_SN(f_type_enum_roa) = {
  FC_TYPE(int),
  FC_ID(T_ENUM_ROA),
  .name = "enum roa",
  .compare = COMPARE(uint_cmp(VAL1, VAL2)),
  .hash = HASHVAL(u64_hash0(VAL, HASH_PARAM, seed)),
};

static const struct f_class FC_SN(f_type_enum_aspa) = {
  FC_TYPE(int),
  FC_ID(T_ENUM_ASPA),
  .name = "enum aspa",
  .compare = COMPARE(uint_cmp(VAL1, VAL2)),
  .hash = HASHVAL(u64_hash0(VAL, HASH_PARAM, seed)),
};

static const struct f_class FC_SN(f_type_enum_net_type) = {
  FC_TYPE(int),
  FC_ID(T_ENUM_NET_TYPE),
  .name = "enum net_type",
  .compare = COMPARE(uint_cmp(VAL1, VAL2)),
  .hash = HASHVAL(u64_hash0(VAL, HASH_PARAM, seed)),
};

static const struct f_class FC_SN(f_type_enum_ra_preference) = {
  FC_TYPE(int),
  FC_ID(T_ENUM_RA_PREFERENCE),
  .name = "enum ra_preference",
  .compare = COMPARE(uint_cmp(VAL1, VAL2)),
  .hash = HASHVAL(u64_hash0(VAL, HASH_PARAM, seed)),
};

static const struct f_class FC_SN(f_type_enum_af) = {
  FC_TYPE(int),
  FC_ID(T_ENUM_AF),
  .name = "enum af",
  .compare = COMPARE(uint_cmp(VAL1, VAL2)),
  .hash = HASHVAL(u64_hash0(VAL, HASH_PARAM, seed)),
};

static const struct f_class FC_SN(f_type_enum_mpls_policy) = {
  FC_TYPE(int),
  FC_ID(T_ENUM_MPLS_POLICY),
  .name = "enum mpls_policy",
  .compare = COMPARE(uint_cmp(VAL1, VAL2)),
  .hash = HASHVAL(u64_hash0(VAL, HASH_PARAM, seed)),
};

static const struct f_class FC_SN(f_type_enum_net_evpn_type) = {
  FC_TYPE(int),
  FC_ID(T_ENUM_NET_EVPN_TYPE),
  .name = "enum net_evpn_type",
  .compare = COMPARE(uint_cmp(VAL1, VAL2)),
  .hash = HASHVAL(u64_hash0(VAL, HASH_PARAM, seed)),
};

static const struct f_class FC_SN(f_type_enum_kbr_source) = {
  FC_TYPE(int),
  FC_ID(T_ENUM_KBR_SOURCE),
  .name = "enum kbr_source",
  .compare = COMPARE(uint_cmp(VAL1, VAL2)),
  .hash = HASHVAL(u64_hash0(VAL, HASH_PARAM, seed)),
};

static const struct f_class FC_SN(f_type_enum_empty) = {
  FC_TYPE(int),
  FC_ID(T_ENUM_EMPTY),
  .hidden = true,
  .name = "enum __empty",
  .same = &void_same,
  .hash = HASHVAL(u64_hash0(VAL, HASH_PARAM, seed)),
};

static const struct f_class FC_SN(f_type_enum_hi) = {
  FC_TYPE(int),
  FC_ID(T_ENUM_HI),
  .hidden = true,
  .name = "enum __hi",
};

static const struct f_class FC_SN(f_type_ip) = {
  FC_TYPE(ip_addr),
  FC_ID(T_IP),
  .ea_type = EAF_TYPE_IP_ADDRESS,
  .legacy_kw = true,
  .name = "ip",
  .pretty_name = "IP address",
  .compare = COMPARE(ipa_compare(VAL1, VAL2)),
  .hash = HASHVAL(mem_hash_mix(&seed, &VAL, sizeof VAL), seed),
};

static const struct f_class FC_SN(f_type_prefix) = {
  FC_TYPE(const net_addr *),
  FC_ID(T_NET),
  .legacy_kw = true,
  .name = "prefix",
  .compare = COMPARE(net_compare(VAL1, VAL2)),
  .hash = HASHVAL(mem_hash_mix_num(&seed, net_hash(VAL)), seed),
};

static const struct f_class FC_SN(f_type_string) = {
  FC_TYPE(const char *),
  FC_ID(T_STRING),
  .ea_type = EAF_TYPE_STRING,
  .legacy_kw = true,
  .name = "string",
  .pretty_name = "String",
  .compare = COMPARE(({ int i = strcmp(VAL1, VAL2); (i > 0) - (i < 0); })),
  .hash = HASHVAL(mem_hash_mix_str(&seed, VAL), seed),
};

static const struct f_class FC_SN(f_type_bytestring) = {
  FC_TYPE(const struct adata *),
  FC_ID(T_BYTESTRING),
  .ea_type = EAF_TYPE_OPAQUE,
  .legacy_kw = true,
  .name = "bytestring",
  .pretty_name = "Bytestring",
  .compare = COMPARE(bytestring_compare(VAL1, VAL2)),
  .hash = HASHVAL(mem_hash_mix(&seed, VAL->data, VAL->length), seed),
};

static const struct f_class FC_SN(f_type_bgpmask) = {
  FC_TYPE(const struct f_path_mask *),
  FC_ID(T_PATH_MASK),
  .legacy_kw = true,
  .name = "bgpmask",
  .same = SAME(pm_same(VAL1, VAL2)),
  .hash = HASHVAL(mem_hash_mix(&seed, VAL, sizeof *VAL + VAL->len * sizeof *VAL->item), seed),
};

static const struct f_class FC_SN(f_type_bgpmask_item) = {
  FC_TYPE(struct f_path_mask_item),
  FC_ID(T_PATH_MASK_ITEM),
  .hidden = true,
  .name = "bgpmask_item",
  .same = SAME(pmi_same(&(VAL1), &(VAL2))),
};

static const struct f_class FC_SN(f_type_bgppath) = {
  FC_TYPE(const struct adata *),
  FC_ID(T_PATH),
  .ea_type = EAF_TYPE_AS_PATH,
  .legacy_kw = true,
  .name = "bgppath",
  .empty = { .type = T_PATH, .val.ad = &null_adata },
  .compare = COMPARE(as_path_compare(VAL1, VAL2)),
  .hash = HASHVAL(mem_hash_mix(&seed, VAL->data, VAL->length), seed),
};

static const struct f_class FC_SN(f_type_clist) = {
  FC_TYPE(const struct adata *),
  FC_ID(T_CLIST),
  .ea_type = EAF_TYPE_INT_SET,
  .legacy_kw = true,
  .name = "clist",
  .empty = { .type = T_CLIST, .val.ad = &null_adata },
  .same = SAME(adata_same(VAL1, VAL2)),
  .hash = HASHVAL(mem_hash_mix(&seed, VAL->data, VAL->length), seed),
};

static const struct f_class FC_SN(f_type_ec) = {
  FC_TYPE(u64),
  FC_ID(T_EC),
  .legacy_kw = true,
  .name = "ec",
  .compare = COMPARE(u64_cmp(VAL1, VAL2)),
  .hash = HASHVAL(u64_hash0(VAL, HASH_PARAM, seed)),
};

static const struct f_class FC_SN(f_type_eclist) = {
  FC_TYPE(const struct adata *),
  FC_ID(T_ECLIST),
  .ea_type = EAF_TYPE_EC_SET,
  .legacy_kw = true,
  .name = "eclist",
  .empty = { .type = T_ECLIST, .val.ad = &null_adata },
  .same = SAME(adata_same(VAL1, VAL2)),
  .hash = HASHVAL(mem_hash_mix(&seed, VAL->data, VAL->length), seed),
};

static const struct f_class FC_SN(f_type_lc) = {
  FC_TYPE(lcomm),
  FC_ID(T_LC),
  .legacy_kw = true,
  .name = "lc",
  .compare = COMPARE(lcomm_cmp(VAL1, VAL2)),
  .hash = HASHVAL(u32_hash0(VAL.asn, HASH_PARAM, u32_hash0(VAL.ldp1, HASH_PARAM, u32_hash0(VAL.ldp2, HASH_PARAM, seed)))),
};

static const struct f_class FC_SN(f_type_lclist) = {
  FC_TYPE(const struct adata *),
  FC_ID(T_LCLIST),
  .ea_type = EAF_TYPE_LC_SET,
  .legacy_kw = true,
  .name = "lclist",
  .empty = { .type = T_LCLIST, .val.ad = &null_adata },
  .same = SAME(adata_same(VAL1, VAL2)),
  .hash = HASHVAL(mem_hash_mix(&seed, VAL->data, VAL->length), seed),
};

static const struct f_class FC_SN(f_type_rd) = {
  FC_TYPE(vpn_rd),
  FC_ID(T_RD),
  .legacy_kw = true,
  .name = "rd",
  .compare = COMPARE(rd_compare(VAL1, VAL2)),
  .hash = HASHVAL(rd_hash0(VAL, HASH_PARAM, seed)),
};

static const struct f_class FC_SN(f_type_mac) = {
  FC_TYPE(mac_addr),
  FC_ID(T_MAC),
  .legacy_kw = true,
  .name = "mac",
  .compare = COMPARE(mac_compare(VAL1, VAL2)),
  .hash = HASHVAL(mem_hash_mix(&seed, &VAL, sizeof VAL), seed),
};

static const struct f_class FC_SN(f_type_route) = {
  FC_TYPE(struct rte *),
  FC_ID(T_ROUTE),
  .legacy_kw = true,
  .name = "route",
  .empty = { .type = T_ROUTE, },
  .same = SAME(VAL1 == VAL2),
};

static const struct f_class FC_SN(f_type_routes) = {
  FC_TYPE(struct rte *),
  FC_ID(T_ROUTES_BLOCK),
  .name = "routes",
  .same = SAME(VAL1 == VAL2),
};

#include "filter/class-m4-auto-post.c"

const struct f_class *
f_type_get_class(enum f_type t)
{
  return (t < ARRAY_SIZE(f_base_types)) ? f_base_types[t] : NULL;
}
