## TODO: find out how to generate this file by another yaml file.
## Gitlab can do it but it is a stupid idea to mess with this
## when releasing 4 versions at once. See ya later!
##                                              -- Maria, April 2025

variables:
  DEBIAN_FRONTEND: noninteractive
  LC_ALL: C.UTF-8
  GIT_STRATEGY: fetch
  DOCKER_CMD: docker --config="$HOME/.docker/$CI_JOB_ID/"
  IMG_BASE: registry.nic.cz/labs/bird
  TOOLS_DIR: /home/gitlab-runner/bird-tools
  STAYRTR_BINARY: /usr/bin/stayrtr

stages:
  - consistency
  - image
  - child-prepare
  - build
  - pkg
  - test
  - release

## Common rules
# Ignore WIP commits
.never_wip: &never_wip
  if: $CI_COMMIT_MESSAGE =~ /^(fixup! )*WIP/
  when: never
# Run for stable branches
.if_stable: &if_stable
  if: $CI_COMMIT_BRANCH =~ /^(stable-.*|thread-next|master)$/
  when: always

## Consistency checks for stable branches
commit-messages:
  stage: consistency
  script:
  - tools/git-check-commits
  rules:
  - *if_stable
  - when: never

## Child pipelines
.child-prepare: &child-prepare
  stage: child-prepare
  script:
    - apk add --update --no-cache python3 git
    - python3 -m venv venv
    - . venv/bin/activate
    - python3 -m ensurepip
    - pip3 install --no-cache --upgrade jinja2 pyyaml
    - mkdir -p obj/gitlab
    - 'cd misc/gitlab && python3 pipeline.py $TARGET > ../../obj/gitlab/$TARGET.yml'
  artifacts:
    paths:
      - obj/gitlab/*
  tags:
    - linux
    - docker

## Pipeline for builds in various Linux distributions (in Docker images)
distro-build-prepare:
  <<: *child-prepare
  variables:
    TARGET: distro-build

distro-build-run:
  stage: build
  trigger:
    include:
      - artifact: obj/gitlab/distro-build.yml
        job: distro-build-prepare
    strategy: depend

## Pipeline for partial builds (now only in Linux but should be also done in BSDs)
partial-build-prepare:
  <<: *child-prepare
  variables:
    TARGET: partial-build

partial-build-run:
  stage: build
  trigger:
    include:
      - artifact: obj/gitlab/partial-build.yml
        job: partial-build-prepare
    strategy: depend

## Pipeline for release scripts
release-prepare:
  <<: *child-prepare
  variables:
    TARGET: release

release-run:
  stage: build
  trigger:
    include:
      - artifact: obj/gitlab/release.yml
        job: release-prepare
    strategy: depend

## Pipeline for Netlab tests
netlab-prepare:
  <<: *child-prepare
  variables:
    TARGET: netlab

netlab-run:
  stage: build
  trigger:
    include:
      - artifact: obj/gitlab/netlab.yml
        job: netlab-prepare
    strategy: depend

## BIRDlab tests

.build-birdlab-base: &build-birdlab-base
  stage: build
  script:
    - export BRANCH=$CI_COMMIT_BRANCH
    - autoreconf
    - ./configure $CONFIGURE_OPTIONS
    - gmake
    - gmake check
  rules:
  - *never_wip
  - when: always

# There is no docker for BSD's, these are proper virtuals in QEMU.
build-birdlab-freebsd-13:
  <<: *build-birdlab-base
  tags:
    - birdlab-freebsd-13
    - amd64

build-birdlab-freebsd-13-netlink:
  <<: *build-birdlab-base
  variables:
    CONFIGURE_OPTIONS: --with-sysconfig=bsd-netlink --disable-client
  tags:
    - birdlab-freebsd-13
    - amd64

build-birdlab-freebsd-14:
  <<: *build-birdlab-base
  tags:
    - birdlab-freebsd-14
    - amd64

build-birdlab-freebsd-14-netlink:
  <<: *build-birdlab-base
  variables:
    CONFIGURE_OPTIONS: --with-sysconfig=bsd-netlink --disable-client
  tags:
    - birdlab-freebsd-14
    - amd64

build-birdlab-openbsd-71:
  <<: *build-birdlab-base
  variables:
    AUTOCONF_VERSION: "2.71"
  tags:
    - birdlab-openbsd-71
    - amd64

# We have also some virtuals for these but there are working dockers as well
# so no need to bother again
#build-birdlab-debian-11:
#  <<: *build-birdlab-base
#  tags:
#    - birdlab-debian-11
#    - amd64
#
#build-birdlab-centos-08:
#  <<: *build-birdlab-base
#  tags:
#    - birdlab-centos-08
#    - amd64
#
#build-birdlab-fedora-37:
#  <<: *build-birdlab-base
#  tags:
#    - birdlab-fedora-37
#    - amd64

# Release confirmation job for tag pushing. As soon as we finish our web
# deployment automatic machinery, clicking the button is expected to
# publish the release info on our website.
#
# We are not there yet tho, too many other fish to fry.

publish-release:
  stage: release
  script:
  - "true"
  rules:
  - if: '$CI_COMMIT_TAG'
    when: manual
  - when: never
