## TODO: find out how to generate this file by another yaml file.
## Gitlab can do it but it is a stupid idea to mess with this
## when releasing 4 versions at once. See ya later!
##                                              -- Maria, April 2025

variables:
  DEBIAN_FRONTEND: noninteractive
  LC_ALL: C.UTF-8
  GIT_STRATEGY: fetch
  DOCKER_CMD: docker --config="$HOME/.docker/$CI_JOB_ID/"
  IMG_BASE: registry.nic.cz/labs/bird
  TOOLS_DIR: /home/gitlab-runner/bird-tools
  STAYRTR_BINARY: /usr/bin/stayrtr

stages:
  - consistency
  - image
  - child-prepare
  - build
  - pkg
  - test
  - release

## Common rules
# Ignore WIP commits
.never_wip: &never_wip
  if: $CI_COMMIT_MESSAGE =~ /^(fixup! )*WIP/
  when: never
# Run for stable branches
.if_stable: &if_stable
  if: $CI_COMMIT_BRANCH =~ /^(stable-.*|thread-next|master)$/
  when: always

## Consistency checks for stable branches
commit-messages:
  stage: consistency
  script:
  - tools/git-check-commits
  rules:
  - *if_stable
  - when: never

## Child pipelines
.child-prepare: &child-prepare
  stage: child-prepare
  script:
    - apk add --update --no-cache python3 git
    - python3 -m venv venv
    - . venv/bin/activate
    - python3 -m ensurepip
    - pip3 install --no-cache --upgrade jinja2 pyyaml
    - mkdir -p obj/gitlab
    - 'cd misc/gitlab && python3 pipeline.py $TARGET > ../../obj/gitlab/$TARGET.yml'
  artifacts:
    paths:
      - obj/gitlab/*
  tags:
    - linux
    - docker

distro-build-prepare:
  <<: *child-prepare
  variables:
    TARGET: distro-build

distro-build-run:
  stage: build
  trigger:
    include:
      - artifact: obj/gitlab/distro-build.yml
        job: distro-build-prepare
    strategy: depend

release-prepare:
  <<: *child-prepare
  variables:
    TARGET: release

release-run:
  stage: build
  trigger:
    include:
      - artifact: obj/gitlab/release.yml
        job: release-prepare
    strategy: depend


## Build stage
#
# Now we compile and run unit tests ... in every single distribution.
# Every task needs its docker, see above.

.build: &build-base
  stage: build
  script:
  - export BRANCH=$CI_COMMIT_BRANCH
  - autoreconf
  - ./configure CPPFLAGS="$CPPFLAGS" LDFLAGS="$LDFLAGS" $CONFIGURE_OPTIONS
  # Detect which make is available
  - MAKE=make
  - which gmake 2>/dev/null >/dev/null && MAKE=gmake
  - $MAKE
  - $MAKE check
  # Build docs when tools are available
  - if which linuxdoc pdflatex sgmlsasp >/dev/null ; then $MAKE docs ; fi
  rules:
  - *never_wip
  - when: always

.build-linux: &build-linux
  <<: *build-base
  tags:
    - docker
    - linux
    - amd64

# Testing builds for just a single protocol each time

.build-only: &build-only
  <<: *build-linux
  image: registry.nic.cz/labs/bird:debian-12-amd64

build-only-aggregator:
  <<: *build-only
  variables:
    CONFIGURE_OPTIONS: --with-protocols=aggregator

build-only-babel:
  <<: *build-only
  variables:
    CONFIGURE_OPTIONS: --with-protocols=babel

build-only-bfd:
  <<: *build-only
  variables:
    CONFIGURE_OPTIONS: --with-protocols=bfd

build-only-bgp:
  <<: *build-only
  variables:
    CONFIGURE_OPTIONS: --with-protocols=bgp

build-only-bgp-bmp:
  <<: *build-only
  variables:
    CONFIGURE_OPTIONS: --with-protocols=bgp,bmp

build-only-l3vpn:
  <<: *build-only
  variables:
    CONFIGURE_OPTIONS: --with-protocols=l3vpn

build-only-mrt:
  <<: *build-only
  variables:
    CONFIGURE_OPTIONS: --with-protocols=mrt

build-only-ospf:
  <<: *build-only
  variables:
    CONFIGURE_OPTIONS: --with-protocols=ospf

build-only-pipe:
  <<: *build-only
  variables:
    CONFIGURE_OPTIONS: --with-protocols=pipe

build-only-radv:
  <<: *build-only
  variables:
    CONFIGURE_OPTIONS: --with-protocols=radv

build-only-rip:
  <<: *build-only
  variables:
    CONFIGURE_OPTIONS: --with-protocols=rip

build-only-rpki:
  <<: *build-only
  variables:
    CONFIGURE_OPTIONS: --with-protocols=rpki

build-only-static:
  <<: *build-only
  variables:
    CONFIGURE_OPTIONS: --with-protocols=static

build-netlab:
  stage: build
  variables:
    BDIR: build-netlab
  tags:
    - netlab
    - amd64
  script:
    - autoreconf
    - mkdir $BDIR
    - cd $BDIR
    - ../configure
    - BRANCH=$CI_COMMIT_BRANCH make
  artifacts:
    paths:
      - $BDIR/bird
      - $BDIR/birdc
    expire_in: 2 hours
  rules:
  - *never_wip
  - when: always

.test: &test-base
  stage: test
  needs: [build-netlab]
  tags:
    - netlab
    - amd64
  script:
    - DIR=$(pwd)
    - cd $TOOLS_DIR
    - sudo git clean -fx
    - git pull --ff-only
    - mv $DIR/build-netlab/* netlab/common/
    - ln -s $STAYRTR_BINARY netlab/common/stayrtr
    - cd netlab
    - sudo ./stop
    - sudo ./runtest -s v2 -m check $TEST_NAME
  rules:
  - *never_wip
  - when: always

test-ospf-base:
  <<: *test-base
  variables:
    TEST_NAME: cf-ospf-base

test-ospf-default:
  <<: *test-base
  variables:
    TEST_NAME: cf-ospf-default

test-ospf-priority:
  <<: *test-base
  variables:
    TEST_NAME: cf-ospf-priority

test-ospf-nbma:
  <<: *test-base
  variables:
    TEST_NAME: cf-ospf-nbma

test-ospf-ptmp:
  <<: *test-base
  variables:
    TEST_NAME: cf-ospf-ptmp

test-ospf-authentication:
  <<: *test-base
  variables:
    TEST_NAME: cf-ospf-authentication

test-ospf-bfd:
  <<: *test-base
  variables:
    TEST_NAME: cf-ospf-bfd

test-ospf-custom:
  <<: *test-base
  variables:
    TEST_NAME: cf-ospf-custom

test-ospf-area:
  <<: *test-base
  variables:
    TEST_NAME: cf-ospf-area

test-ospf-vrf:
  <<: *test-base
  variables:
    TEST_NAME: cf-ospf-vrf

test-bgp-base:
  <<: *test-base
  variables:
    TEST_NAME: cf-bgp-base

test-bgp-auth:
  <<: *test-base
  variables:
    TEST_NAME: cf-bgp-auth

test-bgp-int:
  <<: *test-base
  variables:
    TEST_NAME: cf-bgp-int

test-bgp-merged:
  <<: *test-base
  variables:
    TEST_NAME: cf-bgp-merged

test-bgp-flowspec:
  <<: *test-base
  variables:
    TEST_NAME: cf-bgp-flowspec

test-bgp-rs-multitab:
  <<: *test-base
  variables:
    TEST_NAME: cf-bgp-rs-multitab

test-bgp-rs-singletab:
  <<: *test-base
  variables:
    TEST_NAME: cf-bgp-rs-singletab

test-ebgp-loop:
  <<: *test-base
  variables:
    TEST_NAME: cf-ebgp-loop

test-ebgp-star:
  <<: *test-base
  variables:
    TEST_NAME: cf-ebgp-star

test-ebgp-role:
  <<: *test-base
  variables:
    TEST_NAME: cf-ebgp-role

test-ebgp-graceful:
  <<: *test-base
  variables:
    TEST_NAME: cf-ebgp-graceful

test-ebgp-import-limit:
  <<: *test-base
  variables:
    TEST_NAME: cf-ebgp-import-limit

test-ebgp-hostname:
  <<: *test-base
  variables:
    TEST_NAME: cf-ebgp-hostname

test-ibgp-loop:
  <<: *test-base
  variables:
    TEST_NAME: cf-ibgp-loop

test-ibgp-loop-big:
  <<: *test-base
  variables:
    TEST_NAME: cf-ibgp-loop-big

test-ibgp-flat:
  <<: *test-base
  variables:
    TEST_NAME: cf-ibgp-flat

test-babel-base:
  <<: *test-base
  variables:
    TEST_NAME: cf-babel-base

test-babel-auth:
  <<: *test-base
  variables:
    TEST_NAME: cf-babel-auth

test-rip-base:
  <<: *test-base
  variables:
    TEST_NAME: cf-rip-base

test-kernel-learn:
  <<: *test-base
  variables:
    TEST_NAME: cf-kernel-learn

test-mpls-bgp:
  <<: *test-base
  variables:
    TEST_NAME: cf-mpls-bgp

test-mpls-bgp-l3vpn:
  <<: *test-base
  variables:
    TEST_NAME: cf-mpls-bgp-l3vpn


.build-birdlab-base: &build-birdlab-base
  stage: build
  script:
    - export BRANCH=$CI_COMMIT_BRANCH
    - autoreconf
    - ./configure $CONFIGURE_OPTIONS
    - gmake
    - gmake check
  rules:
  - *never_wip
  - when: always

# There is no docker for BSD's, these are proper virtuals in QEMU.
build-birdlab-freebsd-13:
  <<: *build-birdlab-base
  tags:
    - birdlab-freebsd-13
    - amd64

build-birdlab-freebsd-13-netlink:
  <<: *build-birdlab-base
  variables:
    CONFIGURE_OPTIONS: --with-sysconfig=bsd-netlink --disable-client
  tags:
    - birdlab-freebsd-13
    - amd64

build-birdlab-freebsd-14:
  <<: *build-birdlab-base
  tags:
    - birdlab-freebsd-14
    - amd64

build-birdlab-freebsd-14-netlink:
  <<: *build-birdlab-base
  variables:
    CONFIGURE_OPTIONS: --with-sysconfig=bsd-netlink --disable-client
  tags:
    - birdlab-freebsd-14
    - amd64

build-birdlab-openbsd-71:
  <<: *build-birdlab-base
  variables:
    AUTOCONF_VERSION: "2.71"
  tags:
    - birdlab-openbsd-71
    - amd64

# We have also some virtuals for these but there are working dockers as well
# so no need to bother again
#build-birdlab-debian-11:
#  <<: *build-birdlab-base
#  tags:
#    - birdlab-debian-11
#    - amd64
#
#build-birdlab-centos-08:
#  <<: *build-birdlab-base
#  tags:
#    - birdlab-centos-08
#    - amd64
#
#build-birdlab-fedora-37:
#  <<: *build-birdlab-base
#  tags:
#    - birdlab-fedora-37
#    - amd64

# Release confirmation job for tag pushing. As soon as we finish our web
# deployment automatic machinery, clicking the button is expected to
# publish the release info on our website.
#
# We are not there yet tho, too many other fish to fry.

publish-release:
  stage: release
  script:
  - "true"
  rules:
  - if: '$CI_COMMIT_TAG'
    when: manual
  - when: never
