# Fetch the version information
ifeq ($(VERSION),)
VERSION := $(strip $(shell $(srcdir)/tools/version))
endif
CFLAGS += -DBIRD_VERSION='"$(VERSION)"'

all: daemon cli

daemon: $(daemon)
cli: $(client)

$(daemon): LIBS += $(DAEMON_LIBS)

# Submakefile directory magic
s = $(dir $(lastword $(MAKEFILE_LIST)))
ifeq ($(srcdir),.)
  o = $(objdir)/$(s)
else
  o = $(patsubst $(srcdir)%,$(objdir)%,$(s))
endif

# conf/Makefile declarations needed for all other modules
conf-lex-targets := $(addprefix $(objdir)/conf/,cf-lex.o)
conf-y-targets := $(addprefix $(objdir)/conf/,cf-parse.y keywords.h commands.h)
cf-local = $(conf-y-targets): $(s)config.Y

src-o-files = $(patsubst %.c,$(o)%.o,$(src))
tests-target-files = $(patsubst %.c,$(o)%,$(tests_src))

all-daemon = $(daemon): $(obj)
all-client = $(client): $(obj)

# Include main Makefiles of the directories
include $(addsuffix /Makefile,$(addprefix $(srcdir)/,$(subdirs)))

# Generic rules
# Object file rules
$(objdir)/%.o: $(srcdir)/%.c $(srcdir)/mk/build.mk | prepare
	$(E)echo CC -o $@ -c $<
	$(Q)$(CC) $(CFLAGS) -MMD -MP -o $@ -c $<

$(objdir)/%.o: $(objdir)/%.c $(srcdir)/mk/build.mk | prepare
	$(E)echo CC -o $@ -c $<
	$(Q)$(CC) $(CFLAGS) -MMD -MP -o $@ -c $<

# Debug: Preprocessed source rules
$(objdir)/%.E: $(srcdir)/%.c $(srcdir)/mk/build.mk | prepare
	$(E)echo CC -o $@ -E $<
	$(Q)$(CC) $(CFLAGS) -MMD -MP -o $@ -E $<

$(objdir)/%.E: $(objdir)/%.c $(srcdir)/mk/build.mk | prepare
	$(E)echo CC -o $@ -E $<
	$(Q)$(CC) $(CFLAGS) -MMD -MP -o $@ -E $<

# Debug: Assembler object rules
$(objdir)/%.S: $(srcdir)/%.c $(srcdir)/mk/build.mk | prepare
	$(E)echo CC -o $@ -S $<
	$(Q)$(CC) $(CFLAGS) -MMD -MP -o $@ -S $<

$(objdir)/%.S: $(objdir)/%.c $(srcdir)/mk/build.mk | prepare
	$(E)echo CC -o $@ -S $<
	$(Q)$(CC) $(CFLAGS) -MMD -MP -o $@ -S $<

# Finally include the computed dependencies:
DEPS = $(shell find $(objdir) -name '*.d')

# ## if there is at least one non-clean goal
ifneq ($(filter-out $(cleangoals),$(MAKECMDGOALS)),)
-include $(DEPS)
endif

# ## if the implicit goal is called
ifeq ($(MAKECMDGOALS),)
-include $(DEPS)
endif

# Rule for pre-generating all generated includables
# before compiling any C file
prepare: $(objdir)/sysdep/paths.h

$(client) $(daemon):
	$(E)echo LD $(LDFLAGS) -o $@ $^ $(LIBS)
	$(Q)$(CC) $(LDFLAGS) -o $@ $^ $(LIBS)

$(objdir)/sysdep/paths.h: $(BUILDDIR)/Makefile $(srcdir)/mk/build.mk
	$(E)echo GEN $@
	$(Q)echo  >$@ "/* Generated by Makefile, don't edit manually! */"
	$(Q)echo >>$@ "#define PATH_CONFIG_FILE \"$(default_config_file)\""
	$(Q)echo >>$@ "#define PATH_CONTROL_SOCKET \"$(default_control_socket)\""
	$(Q)echo $(if $(iproutedir),>>$@ "#define PATH_IPROUTE_DIR \"$(iproutedir)\"")

.PHONY: all daemon cli prepare docs userdocs progdocs

tags:
	cd $(srcdir) ; etags -lc `find $(subdirs) -name '*.[chY]'`

cscope:
	cd $(srcdir) ; find $(subdirs) -name '*.[chY]' > cscope.files ; cscope -b

.PHONY: tags cscope
