from aiocoap import Context, Message, FETCH, iPATCH, GET, PUT, POST, DELETE
from aiocoap.numbers.contentformat import ContentFormat
from aiocoap.numbers.codes import Code

from dataclasses import dataclass
from pathlib import Path
import subprocess

import pytest
pytest_plugin = ('pytest_asyncio',)

# Define aiocoap COAP Content-Format, these should get IANA preallocation soon
YANG_IDENTIFIERS_CF_ID = 65000
YANG_INSTANCES_CF_ID = 65001
_MT_YANG_IDENTIFIERS = ('application/yang-identifiers', 'cbor-seq')
_MT_YANG_INSTANCES = ('application/yang-instances', 'cbor-seq')

ContentFormat.define(
    YANG_IDENTIFIERS_CF_ID,
    media_type=_MT_YANG_IDENTIFIERS[0],
    encoding=_MT_YANG_IDENTIFIERS[1]
)
ContentFormat.define(
    YANG_INSTANCES_CF_ID,
    media_type=_MT_YANG_INSTANCES[0],
    encoding=_MT_YANG_INSTANCES[1]
)
YANG_IDS = ContentFormat.by_media_type(*_MT_YANG_IDENTIFIERS)
YANG_INST = ContentFormat.by_media_type(*_MT_YANG_INSTANCES)
YANG_DATA_SIDS = ContentFormat.by_media_type("application/yang-data+cbor; id=sid")

async def get_ctx():
    "Helper method"

    return await Context.create_client_context()

@dataclass
class Config:
    "Configuration data holding several URL for CORECONF+COAP"

    url: str
    datastore_url: str
    rpc_url: str
    event_stream_url: str
    yang_lib_url: str

class TestContentFormat:
    """Test correctness of used COAP Content-Formats by bird implementation of CORECONF.
    This should be soon generated by uytc."""

    @pytest.fixture(scope="class", autouse=True)
    @classmethod
    def urls(cls):
        url = "coap+tcp://localhost"
        datastore_url = url + "/c"
        rpc_url = url + "/c"
        event_stream_url = url + "/s"
        yang_lib_url = url + "/yl"

        bird = Path("../bird")
        birdc = Path("../birdc")
        if not bird.exists() or not birdc.exists():
            raise ValueError("Missing bird or birdc executable, please run this test inside the /yang subdirectory")

        try:
            cls.check_bird_health()
            cls.stop_bird()
        except ValueError:
            pass
             
        cls.start_bird()

        config = Config(url, datastore_url, rpc_url, event_stream_url, yang_lib_url)
        yield config

        cls.stop_bird()

    @classmethod
    def check_bird_health(cls):
        proc = subprocess.run(["../birdc", "-l", "status"])
        if not proc:
            raise ValueError("bird is not responsive")
        
    @classmethod
    def start_bird(cls):
        print("start bird")
        proc = subprocess.run(["../bird", "-c", "mini.conf", "-l"], capture_output=True)
        if proc.returncode != 0:
            raise ValueError("Failed to start bird")

    @classmethod
    def stop_bird(cls):
        print("stop bird")
        proc = subprocess.run(["../birdc", "-l", "down"])
        if proc.returncode != 0:
            raise ValueError("Failed to stop bird")

    @pytest.mark.asyncio
    async def test_datastore_fetch(self, urls):
        ctx = await get_ctx()
        req = Message(code=FETCH,
                      uri=urls.datastore_url,
                      content_format=YANG_IDS)

        res = await ctx.request(req).response
        assert res.opt.content_format == YANG_INST

    @pytest.mark.asyncio
    async def test_datastore_ipatch(self, urls):
        ctx = await get_ctx()
        req = Message(code=iPATCH,
                      uri=urls.datastore_url,
                      content_format=YANG_INST)

        res = await ctx.request(req).response
        assert res.opt.content_format is None

    @pytest.mark.asyncio
    async def test_datastore_get(self, urls):
        ctx = await get_ctx()
        req = Message(code=GET,
                      uri=urls.datastore_url,
                      content_format=None)

        res = await ctx.request(req).response
        assert res.opt.content_format == YANG_DATA_SIDS

    @pytest.mark.asyncio
    async def test_datastore_put(self, urls):
        ctx = await get_ctx()
        req = Message(code=PUT,
                      uri=urls.datastore_url,
                      content_format=YANG_DATA_SIDS)

        res = await ctx.request(req).response
        assert res.opt.content_format is None

    @pytest.mark.asyncio
    async def test_datastore_post(self, urls):
        ctx = await get_ctx()
        req = Message(code=POST,
                      uri=urls.datastore_url,
                      content_format=YANG_DATA_SIDS)

        res = await ctx.request(req).response
        assert res.opt.content_format is None

    @pytest.mark.asyncio
    async def test_datastore_delete(self, urls):
        ctx = await get_ctx()
        req = Message(code=DELETE,
                      uri=urls.datastore_url,
                      content_format=None)

        res = await ctx.request(req).response
        assert res.opt.content_format is None

    @pytest.mark.asyncio
    async def test_event_stream_get(self, urls):
        ctx = await get_ctx()
        req = Message(code=GET,
                      uri=urls.event_stream_url,
                      content_format=None,
                      observe=0)

        res = await ctx.request(req).response
        assert res.opt.content_format == YANG_INST

    @pytest.mark.asyncio
    async def test_event_stream_fetch(self, urls):
        ctx = await get_ctx()
        req = Message(code=FETCH,
                      uri=urls.event_stream_url,
                      content_format=YANG_IDS,
                      observe=0)

        res = await ctx.request(req).response
        assert res.opt.content_format == YANG_INST

    @pytest.mark.asyncio
    async def test_yang_library_get(self, urls):
        ctx = await get_ctx()
        req = Message(code=GET,
                      uri=urls.yang_lib_url,
                      content_format=None)
    
        res = await ctx.request(req).response
        assert res.opt.content_format == ContentFormat.by_media_type("application/link-format")

    @pytest.mark.asyncio
    async def test_rpc_post(self, urls):
        ctx = await get_ctx()
        req = Message(code=POST,
                      uri=urls.rpc_url,
                      content_format=YANG_INST)

        res = await ctx.request(req).response
        assert res.opt.content_format == YANG_INST

    @pytest.mark.asyncio
    async def test_datastore_fetch_implicit_cf(self, urls):
        ctx = await get_ctx()
        req = Message(code=FETCH,
                      uri=urls.datastore_url,
                      content_format=None) # implicit CF

        res = await ctx.request(req).response
        assert res.opt.content_format == YANG_INST

    @pytest.mark.asyncio
    async def test_datastore_ipatch_implicit_cf(self, urls):
        ctx = await get_ctx()
        req = Message(code=iPATCH,
                      uri=urls.datastore_url,
                      content_format=None) # implicit CF

        res = await ctx.request(req).response
        assert res.opt.content_format is None

    @pytest.mark.asyncio
    async def test_datastore_put_implicit_cf(self, urls):
        ctx = await get_ctx()
        req = Message(code=PUT,
                      uri=urls.datastore_url,
                      content_format=None) # implicit CF

        res = await ctx.request(req).response
        assert res.opt.content_format is None

    @pytest.mark.asyncio
    async def test_datastore_post_implicit_cf(self, urls):
        ctx = await get_ctx()
        req = Message(code=POST,
                      uri=urls.datastore_url,
                      content_format=None) # implicit CF

        res = await ctx.request(req).response
        if res.code == Code.BAD_REQUEST:
            pytest.skip("Not implemented")
        else:
            assert res.opt.content_type is None

    @pytest.mark.asyncio
    async def test_event_stream_get_implicit_cf(self, urls):
        ctx = await get_ctx()
        req = Message(code=GET,
                      uri=urls.event_stream_url,
                      observe=0,
                      content_format=None) # implicit CF

        res = await ctx.request(req).response
        assert res.opt.content_format == YANG_INST

    @pytest.mark.asyncio
    async def test_event_stream_fetch_implicit_cf(self, urls):
        ctx = await get_ctx()
        req = Message(code=FETCH,
                      uri=urls.event_stream_url,
                      observe=0,
                      content_format=None)

        res = await ctx.request(req).response
        assert res.opt.content_format == YANG_INST

    @pytest.mark.asyncio
    async def test_rpc_post_implicit_cf(self, urls):
        ctx = await get_ctx()
        req = Message(code=POST,
                      uri=urls.rpc_url,
                      content_format=None) # implicit CF

        res = await ctx.request(req).response
        if res.code == Code.BAD_REQUEST:
            pytest.skip("Not implemented")
        else:
            assert res.opt.content_format == YANG_INST
            
    @pytest.mark.asyncio
    async def test_datastore_fetch_accept(self, urls):
        for acc in (0, YANG_IDS, YANG_DATA_SIDS):
            ctx = await get_ctx()
            req = Message(code=FETCH,
                          uri=urls.datastore_url,
                          content_format=YANG_IDS,
                          accept=acc)

            res = await ctx.request(req).response
            assert res.code == Code.NOT_ACCEPTABLE

        ctx = await get_ctx()
        req = Message(code=FETCH,
                      uri=urls.datastore_url,
                      content_format=YANG_IDS,
                      accept=YANG_INST)

        res = await ctx.request(req).response
        assert res.code != Code.NOT_ACCEPTABLE

    @pytest.mark.asyncio
    async def test_datastore_ipatch_accept(self, urls):
        for acc in (0, YANG_IDS, YANG_INST, YANG_DATA_SIDS):
            ctx = await get_ctx()
            req = Message(code=iPATCH,
                          uri=urls.datastore_url,
                          content_format=YANG_INST,
                          accept=acc)

            res = await ctx.request(req).response
            assert res.code == Code.NOT_ACCEPTABLE, acc

        ctx = await get_ctx()
        req = Message(code=iPATCH,
                      uri=urls.datastore_url,
                      content_format=YANG_INST)

        res = await ctx.request(req).response
        assert res.code != Code.NOT_ACCEPTABLE

    @pytest.mark.asyncio
    async def test_datastore_get_accept(self, urls):
        for acc in (0, YANG_IDS, YANG_INST):
            ctx = await get_ctx()
            req = Message(code=GET,
                          uri=urls.datastore_url,
                          content_format=None,
                          accept=acc)

            res = await ctx.request(req).response
            assert res.code == Code.NOT_ACCEPTABLE, acc

        ctx = await get_ctx()
        req = Message(code=GET,
                      uri=urls.datastore_url,
                      content_format=None,
                      accept=YANG_DATA_SIDS)

        res = await ctx.request(req).response
        assert res.code != Code.NOT_ACCEPTABLE

    @pytest.mark.asyncio
    async def test_datastore_post_accept(self, urls):
        for acc in (0, YANG_IDS, YANG_INST, YANG_DATA_SIDS):
            ctx = await get_ctx()
            req = Message(code=POST,
                          uri=urls.datastore_url,
                          content_format=YANG_DATA_SIDS,
                          accept=acc)

            res = await ctx.request(req).response
            assert res.code == Code.NOT_ACCEPTABLE

        ctx = await get_ctx()
        req = Message(code=POST,
                      uri=urls.datastore_url,
                      content_format=YANG_DATA_SIDS,
                      accept=None) # no Accept sent
        
        res = await ctx.request(req).response
        assert res.code != Code.NOT_ACCEPTABLE


    @pytest.mark.asyncio
    async def test_datastore_delete_accept(self, urls):
        for acc in (0, YANG_IDS, YANG_INST, YANG_DATA_SIDS):
            ctx = await get_ctx()
            req = Message(code=POST,
                          uri=urls.datastore_url,
                          content_format=None,
                          accept=acc)

            res = await ctx.request(req).response
            assert res.code == Code.NOT_ACCEPTABLE

        ctx = await get_ctx()
        req = Message(code=POST,
                      uri=urls.datastore_url,
                      content_format=None,
                      accept=None) # no Accept sent
        
        res = await ctx.request(req).response
        assert res.code != Code.NOT_ACCEPTABLE

    @pytest.mark.asyncio
    async def test_event_stream_get_accept(self, urls):
        for acc in (0, YANG_IDS, YANG_DATA_SIDS):
            ctx = await get_ctx()
            req = Message(code=POST,
                          uri=urls.event_stream_url,
                          content_format=None,
                          accept=acc)

            res = await ctx.request(req).response
            assert res.code == Code.NOT_ACCEPTABLE


        ctx = await get_ctx()
        req = Message(code=GET,
                      uri=urls.event_stream_url,
                      content_format=None,
                      observe=0,
                      accept=YANG_INST)

        res = await ctx.request(req).response
        assert res.code != Code.NOT_ACCEPTABLE

    @pytest.mark.asyncio
    async def test_event_stream_fetch_accept(self, urls):
        for acc in (0, YANG_IDS, YANG_DATA_SIDS):
            ctx = await get_ctx()
            req = Message(code=FETCH,
                          uri=urls.event_stream_url,
                          content_format=YANG_IDS,
                          accept=acc)

            res = await ctx.request(req).response
            assert res.code == Code.NOT_ACCEPTABLE


        ctx = await get_ctx()
        req = Message(code=FETCH,
                      uri=urls.event_stream_url,
                      content_format=YANG_IDS,
                      observe=0,
                      accept=YANG_INST)

        res = await ctx.request(req).response
        assert res.code != Code.NOT_ACCEPTABLE

    @pytest.mark.asyncio
    async def test_yang_library_get_accept(self, urls):
        for acc in (0, YANG_IDS, YANG_INST):
            ctx = await get_ctx()
            req = Message(code=GET,
                          uri=urls.yang_lib_url,
                          content_format=None,
                          accept=acc)

            res = await ctx.request(req).response
            assert res.code == Code.NOT_ACCEPTABLE

        ctx = await get_ctx()
        req = Message(code=GET,
                      uri=urls.yang_lib_url,
                      content_format=None,
                      accept=YANG_DATA_SIDS)

        res = await ctx.request(req).response
        assert res.code != Code.NOT_ACCEPTABLE

    @pytest.mark.asyncio
    async def test_rpc_post_accept(self, urls):
        for acc in (0, YANG_IDS, YANG_DATA_SIDS):
            ctx = await get_ctx()
            req = Message(code=POST,
                          uri=urls.rpc_url,
                          content_format=YANG_INST,
                          accept=acc)

            res = await ctx.request(req).response
            assert res.code == Code.NOT_ACCEPTABLE

        ctx = await get_ctx()
        req = Message(code=POST,
                      uri=urls.rpc_url,
                      content_format=YANG_INST,
                      accept=YANG_INST)

        res = await ctx.request(req).response
        assert res.code != Code.NOT_ACCEPTABLE

