/*
 *   BIRD -- The Border Gateway Protocol
 *
 *
 *      Parsons, Inc.
 *      (c) 2013-2013
 *
 *	Code can be used under either license:
 *      - Freely distributed and used under the terms of the GNU GPLv2.
 *      - Freely distributed and used under a BSD license, See README.bgpsec.
 */

CF_HDR

/* #include "proto/bgp/bgpsec/bgpsec.h" */

CF_DEFINES

CF_DECLS

CF_KEYWORDS(BGPSEC_CONFIG)

CF_GRAMMAR

CF_CODE

CF_END
