#!/bin/bash

# Get version tag
# Uses 'git log ...' insted of 'git tag --merged' to support older distros
TAG=$(git log --oneline --pretty=format:"%d" \
    | grep -Eo '^ \(tag:\ v[[:digit:]]+.*(,|\))' \
    | head -n 1 \
    | sed -n 's/^ (tag:\ v//p' | sed -n 's/\(,.*\|)\)//p')

# Pack with zeros if needed
TM=$TAG
while [ -n "${TM/*.*.*/}" ]; do
  TM="${TM}.0"
done

if [ "$(git rev-parse HEAD)" == "$(git rev-parse v${TAG})" ]; then
  echo $TM
  exit 0
fi

HASH=$(git rev-parse --short=12 HEAD)

# Add branch info if not passed via command line
if [ -z "${BRANCH}" ]; then
  # There is also --show-current but it's too new to be portable.
  BRANCH=$(git branch | sed -n 's/^[*] //p' | grep -v 'HEAD detached')
fi

# Found a branch
if [ -n "$BRANCH" ]; then
  LENGTH=$(git log --oneline v$TAG..HEAD | wc -l)
  echo $TM+branch.$(echo $BRANCH | sed 's/[^a-zA-Z0-9]/./g').${HASH}
  exit 0
fi

echo $TM+detached.${HASH}
exit 0
